CC = clang
CFLAGS = -O2

.PHONY: clean
vigenere: main.o encrypt.o decrypt.o
	$(CC) main.o encrypt.o decrypt.o
encrypt.o: encrypt.c
	$(CC) $(CFLAGS) -c encrypt.c
encrypt.o: encrypt.c
	$(CC) $(CFLAGS) -c encrypt.c
encrypt.o: encrypt.c
	$(CC) $(CFLAGS) -c encrypt.c

clean:
	rm *.o dice


